---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  global_env: 
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  user: puppet
  secure: ''
  branches:
  - release
  use_litmus: true
  litmus:
    provision_list:
      - travis_deb
      - travis_ub
      - travis_el7
      - travis_el8
      - ---travis_el
  simplecov: true
  notifications:
    slack:
      secure: >-
        EtyvcUX7n4eFSO5B2h5nH0PJXRJv4FpuJ2SjHuMjALlsHiYrNL2JA+t/PXF6xPLvWNs+pH2rWwBAXDzgR4Ltj3eiaN4UuM8Dvt+KmQ1h0ez2eATpmN47aZ4TueiMkSiUVzWT9aSZa85lS1nr9VcRuFLmTLVU1FH01Uu//5uiZkbcU5kODlkFYsT1/oUXEAA2U6MQdANRKYD2RFHb/M21RoV0rIjLy16cwOuHiXMvIb0tzWQOfauKI9byofK/oq+uryLmbAHeT3IYGCqggvrMVf7D6IsQgit83BRWR7hXKd6HNZUbdZvUEdRMtFhu3jH86BVrObNKZ/6aO5/e49yzsaZMXIvNjvQBs3na7TP7GuaDpDAasjaRUgNyGX3v+ALATFScL7RmdBngmLOVCyjPQ3BS5xtiiq7lnbNBPHD+pWaX+0KLcLtwFWUIz15XkLVTfWZ3LafuwSGiOtA5FK3NiuXxtHr6sLJIw5GMj4K0skUsGUR4P7V+fk4iS+nJtqd4wrZRgCEHUFhkPUfkR3c8LYfqqpe5EdFAK2ZBwqy5z3o7jtSLf4Q786OfMp+v9KcqDREMCkIy+zKafpVmSKV77zYZUdJ+F7rNikqWwqIXU9YFNyeWvIKoikc/YfLY0kXFOVU4yIcWS2lmtzS/tSGy0QS1E0PrbvqJ2Ubrk6djJEY=
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  use_litmus: true
  matrix_extras:
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: true
    TARGET_HOST: localhost
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: true
    TARGET_HOST: localhost
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  simplecov: true
Gemfile:
  use_litmus: true
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
Rakefile:
  requires:
  - puppet_pot_generator/rake_tasks
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
